name: fittrack
description: "A takehome assessment by gitstart"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  permission_handler: ^12.0.1
  vibration: ^3.1.3
  flutter_svg: ^2.2.0
  go_router: ^6.0.8
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_native_splash:
  color: "#0D0D10"
  image_android: assets/images/logo/logo2.png
  image_ios: assets/images/logo/logo2.png
  android_12:
    image: assets/images/logo/logo2.png
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/logo/logo1.png"
  image_path_ios: "assets/images/logo/logo1.png"
  image_path: "assets/images/logo/logo1.png"
  background_color: "#0D0D10"
  background_color_ios: "#0D0D10"
  adaptive_icon_background: "#0D0D10"
  adaptive_icon_background_ios: "#0D0D10"
  adaptive_icon_foreground: "assets/images/logo/logo1.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/empty/
    - assets/fonts/
    - assets/lottie/


  fonts:
    - family: Montserrat_Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: Montserrat_Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat_ExtraBlack
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: Montserrat_Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf